### ISSUE TITLE
Hadamard of size 12

### ISSUE THREAD

**Issue by n17s** [Dao-AILab/fast-hadamard-transform#1]
Could you add support for 
```python
h12 = """
+-++++++++++
--+-+-+-+-+-
+++-++----++
+---+--+-++-
+++++-++----
+-+---+--+-+
++--+++-++--
+--++---+--+
++----+++-++
+--+-++---+-
++++----+++-
+-+--+-++---
"""
```
This is constructed using the [Paley II construction](
https://en.wikipedia.org/wiki/Paley_construction) for q=5.

It is a symmetric matrix.

**Comment by tridao** [comment]
Do you want to send a PR?

**Comment by n17s** [comment]
If it's as simple as copying what's there for 20 and 28, I can try. Anything else I should pay attention to?

**Comment by tridao** [comment]
I think it's just copying what's there for 20 and 28.
